### ISSUE TITLE
Migrate staging.hyperbo.la to hyperbola3

### ISSUE THREAD

**Issue by lopopolo** [lopopolo/hyperbola#49]
**Tasks**: 
- [x] put hyperbola1 into read-only mode
- [x] make a final backup on hyperbola1
- [x] do a django dumpdata for hyperbola apps
  
  http://stackoverflow.com/questions/853796/problems-with-contenttypes-when-loading-a-fixture-in-django
  
  ``` console
  $ bin/artifact-exec app/manage.py dumpdata -o /tmp/hyperbola-apps-dump-$(date -u +"%Y-%m-%dT%H%M%SZ").json hyperbola.frontpage hyperbola.lifestream hyperbola.contact
  ```
- [x] install media in `/hyperbola/media` on hyperbola2
- [x] buy hyperbolacdn.com domain
- [x] generate `staging-auth` htpasswd file on hyperbola2 and back up to box
- [x] install mysql on hyperbola2
- [x] store mysql root password in vault
- [x] create hyperbola database and user
- [x] store mysql hyperbola password in vault
- [x] make staging bootstrap artifact (env)
- [x] generate `SECRET_KEY`

  ```python
  import random
  import string
  SECRET_KEY = ''.join([random.SystemRandom().choice("{}{}{}".format(string.ascii_letters, string.digits, string.punctuation)) for i in range(50)])
  ```
- [x] manage.py migrate
- [x] deploy staging artifact
- [x] ensure staging assets are served by hyperbolacdn.com
- [x] ensure media is served by hyperbolacdn.com
- [x] django migrate
  
  ``` console
  $ bin/artifact-exec app/manage.py migrate
  ```
- [x] django load fixture
  
  ``` console
  $ bin/artifact-exec app/manage.py loaddata /tmp/hyperbola-apps-dump-*.json
  ```
- [x] django create admin account (new password)
  
  ``` console
  $ bin/artifact-exec app/manage.py createsuperuser --username lopopolo --email rjl@hyperbo.la
  ```
- [x] create gunicorn systemd service for staging-hyperbola
- [x] verify gunicorn serves pages over socket using curl
- [x] cut dns for staging.hyperbo.la over to hyperbola2
- [x] verify site works.

**Comment by lopopolo** [comment]
hyperbola-production:
```sql
GRANT ALL PRIVILEGES ON hyperbola.* To 'hyperbola-production'@'localhost' IDENTIFIED BY 'password';
```

hyperbola-staging:
```sql
GRANT SELECT ON hyperbola.* TO 'hyperbola-staging'@'localhost' IDENTIFIED BY 'password';
```

**Comment by lopopolo** [comment]
To generate django dump:

1. remove sorl.thumbnail from installed_apps on staging
2. app/manage.py migrate
3. Data dump

  ```
  /hyperbola/tools/bin/current-prod-exec app/manage.py dumpdata --natural-foreign --indent 4 -e sessions -e contenttypes -e auth.Permission -o ~/hyperbola-apps-dump-$(date -u +"%Y-%m-%dT%H%M%SZ").json
  ```

**Comment by lopopolo** [comment]
loaddata required removing this adminlog record (because the sites framework is not enabled):

```json

{
    "model": "admin.logentry",
    "pk": 7,
    "fields": {
        "action_time": "2011-08-05T02:46:03",
        "user": [
            "lopopolo"
        ],
        "content_type": [
            "sites",
            "site"
        ],
        "object_id": "1",
        "object_repr": "hyperbo.la",
        "action_flag": 2,
        "change_message": "Changed domain and name."
    }
},
```

**Comment by lopopolo** [comment]
DNS is cut over on staging and production. Verified by checking the domain assets are being served from

**Comment by lopopolo** [comment]
Shut down hyperbola1

**Comment by lopopolo** [comment]
django admin account and password was transferred in the data dump.
