### ISSUE TITLE
AWS migration

### ISSUE THREAD

**Issue by lopopolo** [lopopolo/hyperbola#63]
## Blocked on

- [x] #56 - App AWS
- [x] #61 - App Ansible
- [x] ~~Terraform SSH Tunnel Port Forwarding - TF-8367~~ Can work around this with an ssh tunnel a la https://github.com/lopopolo/hyperbola-tools/commit/7a93e9ed2

## Tasks

- [x] hyperbola image
  - [x] run gunicorn as `hyperbola-app` user
  - [x] new `SECRET_KEY`
- [x] build AMI
- [x] elasticache redis + dc.hyperbo.la cname to simplify config
- [x] hyperbola alb
- [ ] Access logs for detailed information for all requests made to your load balancer: http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html
- [x] ~~alb forward to well-known resume object~~ django streams s3 object
- [x] rds + dc.hyperbo.la cname
- [x] rds import
